"""Compatibility shim for configuration constants."""

from src.features.config.constants import (
    COMPONENT_CLI,
    COMPONENT_CONFIG,
    COMPONENT_EVIDENCE,
    FEATURE_KEY,
    FILE_TYPE_ENTITIES,
    FILE_TYPE_SOURCES,
    FILE_TYPE_TOPICS,
    STATUS_P1_DONE,
    STATUS_P2_E2E_PASSED,
    STATUS_P3_REFACTORED,
    STATUS_READY,
    VALID_URL_SCHEMES,
    VALIDATION_FAILED,
    VALIDATION_PASSED,
)


__all__ = [
    "FEATURE_KEY",
    "STATUS_P1_DONE",
    "STATUS_P2_E2E_PASSED",
    "STATUS_P3_REFACTORED",
    "STATUS_READY",
    "VALIDATION_PASSED",
    "VALIDATION_FAILED",
    "COMPONENT_CONFIG",
    "COMPONENT_CLI",
    "COMPONENT_EVIDENCE",
    "VALID_URL_SCHEMES",
    "FILE_TYPE_SOURCES",
    "FILE_TYPE_ENTITIES",
    "FILE_TYPE_TOPICS",
]
