"""Compatibility shim for fetch constants."""

from src.features.fetch.constants import (
    DEFAULT_CHUNK_SIZE,
    DEFAULT_MAX_RESPONSE_SIZE_BYTES,
    HTTP_STATUS_BAD_REQUEST,
    HTTP_STATUS_NOT_MODIFIED,
    HTTP_STATUS_OK_MAX,
    HTTP_STATUS_OK_MIN,
    HTTP_STATUS_SERVER_ERROR_MAX,
    HTTP_STATUS_SERVER_ERROR_MIN,
    HTTP_STATUS_TOO_MANY_REQUESTS,
    MAX_RETRY_AFTER_SECONDS,
)


__all__ = [
    "HTTP_STATUS_OK_MIN",
    "HTTP_STATUS_OK_MAX",
    "HTTP_STATUS_NOT_MODIFIED",
    "HTTP_STATUS_BAD_REQUEST",
    "HTTP_STATUS_TOO_MANY_REQUESTS",
    "HTTP_STATUS_SERVER_ERROR_MIN",
    "HTTP_STATUS_SERVER_ERROR_MAX",
    "DEFAULT_MAX_RESPONSE_SIZE_BYTES",
    "DEFAULT_CHUNK_SIZE",
    "MAX_RETRY_AFTER_SECONDS",
]
